import Header from "@/components/header/Header";
import "./globals.scss";
import { Inter, Manrope } from "next/font/google";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={manrope.className}>
				<div>
					<Header />
					<main>{children}</main>
				</div>
			</body>
		</html>
	);
}
